Network_monitoring/urls.py

from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # pour le rechargement en développement
    path("__reload__/", include("django_browser_reload.urls")),

    # l’interface d’administration
    path("admin/", admin.site.urls),

    # toutes les theme statiques (home, acheter, activer, contact…)
    path("", include(("pages.urls", "pages"), namespace="pages")),

    # toutes les vues « système » (dashboard, API, etc.)
    path("systeme/", include(("theme.urls", "theme"), namespace="theme")),

    # toutes les commandee et à la génération de licences.
    path("orders/", include(("orders.urls", "orders"), namespace="orders")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "pages"

urlpatterns = [
    path("", views.home, name='home'),
    path('fonctionnalites/', views.fonctionnalites, name='fonctionnalites'),
    path('versions/', views.versions, name='versions'),
    path('acheter/', views.acheter, name='acheter'),
    path('activer-licence/', views.activer_licence, name='activer_licence'),
    path('contact/', views.contact_view, name='contact'),

    path('register/', views.register, name='register'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),


]

pages/templates/paiement/cancel.html
{% extends './base.html' %}
{% block title %}Erreur de paiement – 2IEM Security{% endblock %}

{% block content %}
<div class="max-w-3xl mx-auto mt-20 text-center px-4">
  <h1 class="text-3xl font-bold text-red-600 mb-6">❌ Paiement échoué</h1>
  <p class="text-gray-700 mb-6">
    Une erreur s’est produite lors de la redirection vers Stripe.<br>
    Veuillez réessayer ou contacter le support technique si le problème persiste.
  </p>
  <a href="{% url 'theme:acheter' %}" class="bg-indigo-600 text-white px-6 py-3 rounded-lg font-semibold hover:bg-indigo-700">
    Revenir à la page d'achat
  </a>
</div>
{% endblock %}

pages/templates/paiement/checkout_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

pages/templates/paiement/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<section class="py-20 bg-green-50 text-center">
  <div class="max-w-2xl mx-auto">
    <h1 class="text-3xl font-bold text-green-700 mb-4">🎉 Paiement réussi !</h1>
    <p class="text-lg text-gray-700 mb-6">
      Merci {{ request.user.username }}. Votre paiement a bien été enregistré.
    </p>
    <a href="/dashboard/" class="bg-green-600 hover:bg-green-700 text-white px-6 py-3 rounded-lg font-semibold">Accéder à mon tableau de bord</a>
  </div>
</section>
</body>
</html>